name: GitHub Commit to QQ

on:
  push:
    branches:
      - master

jobs:
  send-to-qq:
    runs-on: windows-latest
    steps:
      - name: Send commit info to QQ group
        shell: powershell
        run: |
          $COMMIT_MSG = '${{ github.event.head_commit.message }}'
          $COMMIT_URL = '${{ github.event.head_commit.url }}'
          $AUTHOR = '${{ github.event.head_commit.author.name }}'
          $REPO = '${{ github.repository }}'
          $GROUP_ID = 878969691
          $ACCESS_TOKEN = '${{ secrets.ONEBOT_TOKEN }}'

          # 构建消息，并替换换行和引号
          $MESSAGE = "[GitHub] $REPO 有新的提交`n提交者: $AUTHOR`n- $COMMIT_MSG ($COMMIT_URL)"
          $JSON = @{ group_id = $GROUP_ID; message = $MESSAGE } | ConvertTo-Json -Compress

          # 发送
          curl -X POST "http://mc1.top:8083/send_group_msg" -H "Content-Type: application/json" -H "Authorization: Bearer $ACCESS_TOKEN" -d $JSON --connect-timeout 5 --max-time 10
