name: GitHub Commit to QQ

on:
  push:
    branches:
      - master

jobs:
  send-to-qq:
    runs-on: windows-latest
    steps:
      - name: Send commit info to QQ group
        shell: pwsh
        run: |
          $CommitMsg = '${{ github.event.head_commit.message }}'
          $CommitUrl = '${{ github.event.head_commit.url }}'
          $Author = '${{ github.event.head_commit.author.name }}'
          $Repo = '${{ github.repository }}'
          $GroupId = 878969691
          $AccessToken = '${{ secrets.ONEBOT_TOKEN }}'

          # 构建消息
          $Message = "[GitHub] $Repo 有新的提交`n提交者: $Author`n- $CommitMsg ($CommitUrl)"
          $Json = @{ group_id = $GroupId; message = $Message } | ConvertTo-Json -Compress

          # 一行 curl 发送
          curl -X POST "http://mc1.top:8083/send_group_msg" -H "Content-Type: application/json" -H "Authorization: Bearer $AccessToken" -d $Json --connect-timeout 5 --max-time 10
